import React from "react";




// IMPORTANT: NOW THAT WE ARE USING COOKIES FOR AUTHENTICATION AND AUTHORIZATION, WE WILL MAKE SURE EACH REQUEST IS SENT WITH { withCredentials: true }. 
// THIS WILL SEND THE COOKIES WITH EACH REQUEST SO OUR MIDDLEWARE WILL VERIFY WHO IS LOGGED IN.

